export type FundingProduct = {
  slug: string;
  title: string;
  category: "business" | "real-estate" | "personal";
  parentCategorySlug: string;
  fundingType: string;
  solutionFamily: string;
  useCase: string;
  summary: string;
  minAmount: number | null;
  maxAmount: number | null;
  speedToFunding: string;
  creditTier: "good" | "fair" | "subprime" | "n-a";
  minCredit: number | null;
  minMonthlyRevenue: number | null;
  timeInBusiness: string;
  featured: boolean;
};

export const fundingProducts: FundingProduct[] = [
  { slug: "startup-credit-stacking", title: "Startup Credit Stacking", category: "business", parentCategorySlug: "startup-growth-line", fundingType: "Unsecured Line", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Credit-leverage path for founders with strong personal credit and no business revenue yet.", minAmount: 10000, maxAmount: 150000, speedToFunding: "2-3 weeks", creditTier: "good", minCredit: 680, minMonthlyRevenue: 0, timeInBusiness: "0 months", featured: true },
  { slug: "startup-personal-term-loan", title: "Startup Personal Term Loan", category: "personal", parentCategorySlug: "startup-growth-line", fundingType: "Installment Loan", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Personal-credit-backed launch capital for founders with income support.", minAmount: 20000, maxAmount: 250000, speedToFunding: "3-10 days", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "0 months", featured: false },
  { slug: "business-line-of-credit-core", title: "Business Line of Credit", category: "business", parentCategorySlug: "working-capital", fundingType: "Revolving Line", solutionFamily: "Lines of Credit", useCase: "Working Capital", summary: "Recurring-access capital for operators who need flexibility more than a one-time lump sum.", minAmount: 5000, maxAmount: 500000, speedToFunding: "3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "1 year", featured: true },
  { slug: "fast-working-capital-advance", title: "Fast Working Capital Advance", category: "business", parentCategorySlug: "working-capital", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Payroll Gap", summary: "Fast-turn revenue-based capital for urgent cash squeezes and short-cycle needs.", minAmount: 5000, maxAmount: 500000, speedToFunding: "24 hours", creditTier: "subprime", minCredit: 500, minMonthlyRevenue: 10000, timeInBusiness: "6 months", featured: true },
  { slug: "equipment-finance-program", title: "Equipment Finance Program", category: "business", parentCategorySlug: "equipment-financing", fundingType: "Asset Backed", solutionFamily: "Equipment Finance", useCase: "Equipment Purchase", summary: "Asset-backed financing for revenue-producing equipment, vehicles, and machinery.", minAmount: 10000, maxAmount: 50000000, speedToFunding: "1-3 weeks", creditTier: "fair", minCredit: 600, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: true },
  { slug: "commercial-real-estate-loan", title: "Commercial Real Estate Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Real Estate Capital", useCase: "Real Estate Acquisition", summary: "Property-backed capital for acquisitions, refinances, and owner-operator scenarios.", minAmount: 100000, maxAmount: 100000000, speedToFunding: "1-3 months", creditTier: "fair", minCredit: 650, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: true },
  { slug: "sba-growth-loan", title: "SBA Growth Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "Longer-term structured capital for cleaner businesses with stronger documentation.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "1-3 months", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "2 years", featured: true },
  { slug: "personal-term-loan", title: "Personal Term Loan", category: "personal", parentCategorySlug: "startup-growth-line", fundingType: "Installment Loan", solutionFamily: "Personal Liquidity", useCase: "Debt Refinance", summary: "Personal-use liquidity path for stronger-credit borrowers needing quick access.", minAmount: 5000, maxAmount: 500000, speedToFunding: "24-48 hours", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "personal-line-of-credit", title: "Personal Line of Credit", category: "personal", parentCategorySlug: "startup-growth-line", fundingType: "Revolving Line", solutionFamily: "Personal Liquidity", useCase: "Debt Refinance", summary: "Revolving personal liquidity for flexible access instead of fixed disbursement.", minAmount: 5000, maxAmount: 250000, speedToFunding: "3-5 days", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "debt-consolidation-loan", title: "Debt Consolidation Loan", category: "personal", parentCategorySlug: "working-capital", fundingType: "Installment Loan", solutionFamily: "Debt Relief", useCase: "Debt Refinance", summary: "Refinance-oriented personal loan designed to simplify existing obligations.", minAmount: 5000, maxAmount: 500000, speedToFunding: "24-48 hours", creditTier: "fair", minCredit: 660, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "home-equity-loan", title: "Home Equity Loan", category: "personal", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Equity-Backed Capital", useCase: "Debt Refinance", summary: "Equity-backed borrowing for homeowners seeking larger secured liquidity.", minAmount: 20000, maxAmount: 1000000, speedToFunding: "2-4 weeks", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "low-interest-personal-cards", title: "Low-Interest Personal Cards", category: "personal", parentCategorySlug: "startup-growth-line", fundingType: "Credit Card", solutionFamily: "Credit Leverage", useCase: "Startup Capital", summary: "Intro-rate card leverage for borrowers building an early capital stack.", minAmount: 500, maxAmount: 50000, speedToFunding: "1-2 weeks", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "prime-revenue-advance", title: "Prime Revenue Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Revenue-based capital for established businesses needing speed without bank-style friction.", minAmount: 5000, maxAmount: 2000000, speedToFunding: "1-3 days", creditTier: "good", minCredit: 680, minMonthlyRevenue: 15000, timeInBusiness: "2 years", featured: false },
  { slug: "flex-revenue-advance", title: "Flex Revenue Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Revenue-first capital for bruised-credit operators with consistent deposits.", minAmount: 5000, maxAmount: 2000000, speedToFunding: "1-3 days", creditTier: "subprime", minCredit: 550, minMonthlyRevenue: 15000, timeInBusiness: "6 months", featured: false },
  { slug: "instant-micro-advance", title: "Instant Micro Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Payroll Gap", summary: "Small fast-turn advance for very small operators needing immediate relief.", minAmount: 500, maxAmount: 10000, speedToFunding: "instant", creditTier: "subprime", minCredit: null, minMonthlyRevenue: 3000, timeInBusiness: "4 months", featured: false },
  { slug: "business-credit-line-plus", title: "Business Credit Line Plus", category: "business", parentCategorySlug: "working-capital", fundingType: "Revolving Line", solutionFamily: "Lines of Credit", useCase: "Working Capital", summary: "Stronger-credit revolving line with faster access and recurring draw flexibility.", minAmount: 6000, maxAmount: 150000, speedToFunding: "24 hours", creditTier: "good", minCredit: 680, minMonthlyRevenue: 20000, timeInBusiness: "2 years", featured: false },
  { slug: "international-revenue-advance", title: "International Revenue Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Revenue-based advance for qualifying cross-border operating profiles.", minAmount: 5000, maxAmount: 500000, speedToFunding: "1-3 days", creditTier: "subprime", minCredit: 550, minMonthlyRevenue: 10000, timeInBusiness: "6 months", featured: false },
  { slug: "revenue-advance-max", title: "Revenue Advance Max", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Larger advance lane for active businesses prioritizing speed over perfect pricing.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "24 hours", creditTier: "subprime", minCredit: 0, minMonthlyRevenue: 20000, timeInBusiness: "3 months", featured: false },
  { slug: "flexible-business-line", title: "Flexible Business Line", category: "business", parentCategorySlug: "working-capital", fundingType: "Revolving Line", solutionFamily: "Lines of Credit", useCase: "Working Capital", summary: "Smaller revolving line built for cash-flow smoothing and recurring access.", minAmount: 5000, maxAmount: 55000, speedToFunding: "24 hours", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "1 year", featured: false },
  { slug: "founder-launch-loan", title: "Founder Launch Loan", category: "personal", parentCategorySlug: "startup-growth-line", fundingType: "Installment Loan", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Founder-focused launch capital leveraging personal strength instead of business history.", minAmount: 20000, maxAmount: 500000, speedToFunding: "5-7 days", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "0 months", featured: false },
  { slug: "small-business-term-loan-core", title: "Small Business Term Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "General-purpose term capital for growth, stabilization, and broader operating needs.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "24 hours", creditTier: "fair", minCredit: null, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "alternative-equipment-finance", title: "Alternative Equipment Finance", category: "business", parentCategorySlug: "equipment-financing", fundingType: "Asset Backed", solutionFamily: "Equipment Finance", useCase: "Equipment Purchase", summary: "Alternative asset-backed equipment path with more tolerance for imperfect profiles.", minAmount: 20000, maxAmount: 50000000, speedToFunding: "quick approval", creditTier: "subprime", minCredit: 580, minMonthlyRevenue: null, timeInBusiness: "1 year", featured: false },
  { slug: "unsecured-business-term-loan", title: "Unsecured Business Term Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Installment Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "Unsecured installment path for cleaner operators needing structure without hard collateral.", minAmount: 20000, maxAmount: 500000, speedToFunding: "1-2 weeks", creditTier: "good", minCredit: null, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "sba-7a-growth-loan", title: "SBA 7(a) Growth Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "Government-backed growth capital for documented businesses that can survive slower underwriting.", minAmount: 30000, maxAmount: 5000000, speedToFunding: "1-3 months", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "2 years", featured: false },
  { slug: "point-of-sale-consumer-financing", title: "Point-of-Sale Consumer Financing", category: "business", parentCategorySlug: "working-capital", fundingType: "Service", solutionFamily: "Embedded Finance", useCase: "Consumer Financing", summary: "Embedded financing layer for merchants offering payment flexibility at the point of sale.", minAmount: null, maxAmount: null, speedToFunding: "instant", creditTier: "n-a", minCredit: null, minMonthlyRevenue: null, timeInBusiness: "1 year", featured: false },
  { slug: "hard-money-bridge-loan", title: "Hard Money Bridge Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Hard Money", solutionFamily: "Real Estate Capital", useCase: "Fix and Flip", summary: "Asset-driven short-term bridge capital for rehab, flip, and fast-exit strategies.", minAmount: 100000, maxAmount: 50000000, speedToFunding: "2-4 weeks", creditTier: "fair", minCredit: null, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: true },
  { slug: "commercial-mortgage", title: "Commercial Mortgage", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Real Estate Capital", useCase: "Real Estate Acquisition", summary: "Commercial mortgage path for stabilized acquisitions and owner-occupied opportunities.", minAmount: 100000, maxAmount: 50000000, speedToFunding: "2-4 weeks", creditTier: "fair", minCredit: null, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "rental-property-loan", title: "Rental Property Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Real Estate Capital", useCase: "Real Estate Acquisition", summary: "Rental-focused real estate financing for long-term hold investors and income property.", minAmount: 150000, maxAmount: 50000000, speedToFunding: "varies", creditTier: "good", minCredit: 660, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "foreign-national-real-estate-loan", title: "Foreign National Real Estate Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Real Estate Capital", useCase: "Real Estate Acquisition", summary: "Specialized property financing path for qualifying foreign national borrowers.", minAmount: 150000, maxAmount: 50000000, speedToFunding: "varies", creditTier: "n-a", minCredit: null, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "cannabis-business-loan", title: "Cannabis Business Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Specialty Finance", useCase: "Expansion Capital", summary: "Specialty business capital path for cannabis-adjacent operators with stronger revenue.", minAmount: 50000, maxAmount: 5000000, speedToFunding: "1-2 weeks", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 20000, timeInBusiness: "1 year", featured: false },
  { slug: "commercial-truck-finance", title: "Commercial Truck Finance", category: "business", parentCategorySlug: "equipment-financing", fundingType: "Asset Backed", solutionFamily: "Equipment Finance", useCase: "Equipment Purchase", summary: "Truck and fleet financing for transportation businesses and owner-operators.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "1-3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "growth-term-loan", title: "Growth Term Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "Structured term capital for growth projects and smoother cash cycles.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "1-3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "2 years", featured: false },
  { slug: "business-credit-line", title: "Business Credit Line", category: "business", parentCategorySlug: "working-capital", fundingType: "Revolving Line", solutionFamily: "Lines of Credit", useCase: "Working Capital", summary: "Core revolving line with draw-based access for recurring business needs.", minAmount: 10000, maxAmount: 500000, speedToFunding: "1-3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "1 year", featured: false },
  { slug: "sba-expansion-loan", title: "SBA Expansion Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "Longer-term expansion capital for stronger-credit businesses with profitability.", minAmount: 50000, maxAmount: 5000000, speedToFunding: "1-3 months", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "2 years", featured: false },
  { slug: "equipment-financing-core", title: "Equipment Financing", category: "business", parentCategorySlug: "equipment-financing", fundingType: "Asset Backed", solutionFamily: "Equipment Finance", useCase: "Equipment Purchase", summary: "Classic equipment lane for machinery, tools, and productive business assets.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "1-3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "n/a", featured: false },
  { slug: "accounts-receivable-financing", title: "Accounts Receivable Financing", category: "business", parentCategorySlug: "invoice-factoring", fundingType: "Factoring", solutionFamily: "Invoice Finance", useCase: "Invoice Finance", summary: "Receivables-backed liquidity for B2B businesses waiting on invoice payments.", minAmount: 20000, maxAmount: 5000000, speedToFunding: "1-3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "n/a", featured: false },
  { slug: "merchant-working-capital-advance", title: "Merchant Working Capital Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Revenue-based working capital for merchants with ongoing deposits and short-term needs.", minAmount: 20000, maxAmount: 2000000, speedToFunding: "24 hours", creditTier: "subprime", minCredit: 500, minMonthlyRevenue: 15000, timeInBusiness: "6 months", featured: false },
  { slug: "franchise-financing", title: "Franchise Financing", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Specialty Finance", useCase: "Expansion Capital", summary: "Growth and acquisition financing for franchise operators and emerging franchisees.", minAmount: 50000, maxAmount: 5000000, speedToFunding: "2-4 weeks", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "residential-investment-bridge-loan", title: "Residential Investment Bridge Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Hard Money", solutionFamily: "Real Estate Capital", useCase: "Fix and Flip", summary: "Short-term residential bridge capital for project speed and rehab timing.", minAmount: 100000, maxAmount: 5000000, speedToFunding: "2-4 weeks", creditTier: "fair", minCredit: 650, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "startup-funding-program", title: "Startup Funding Program", category: "business", parentCategorySlug: "startup-growth-line", fundingType: "Unsecured Line", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Startup-oriented unsecured line path for founders with strong credit but no business revenue.", minAmount: 10000, maxAmount: 150000, speedToFunding: "2-3 weeks", creditTier: "good", minCredit: 680, minMonthlyRevenue: 0, timeInBusiness: "0 months", featured: false },
  { slug: "commercial-real-estate-financing", title: "Commercial Real Estate Financing", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Real Estate Capital", useCase: "Real Estate Acquisition", summary: "Commercial property financing for larger acquisition, refinance, and income scenarios.", minAmount: 100000, maxAmount: 50000000, speedToFunding: "1-3 months", creditTier: "fair", minCredit: 660, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "ecommerce-growth-plan", title: "Ecommerce Growth Plan", category: "business", parentCategorySlug: "working-capital", fundingType: "Revenue Based", solutionFamily: "Marketplace Capital", useCase: "Ecommerce Inventory", summary: "Marketplace-oriented growth capital for sellers scaling inventory and ad cycles.", minAmount: 10000, maxAmount: 500000, speedToFunding: "24-48 hours", creditTier: "fair", minCredit: null, minMonthlyRevenue: 8500, timeInBusiness: "6 months", featured: true },
  { slug: "marketplace-growth-capital", title: "Marketplace Growth Capital", category: "business", parentCategorySlug: "working-capital", fundingType: "Revenue Based", solutionFamily: "Marketplace Capital", useCase: "Marketplace Cash Flow", summary: "Platform-linked growth capital built for sellers with connected marketplace data.", minAmount: 5000, maxAmount: 2000000, speedToFunding: "instant", creditTier: "fair", minCredit: null, minMonthlyRevenue: 3000, timeInBusiness: "n/a", featured: true },
  { slug: "daily-payout-access", title: "Daily Payout Access", category: "business", parentCategorySlug: "invoice-factoring", fundingType: "Factoring", solutionFamily: "Marketplace Capital", useCase: "Marketplace Cash Flow", summary: "Daily payout acceleration for sellers who need faster access to marketplace revenue.", minAmount: 1000, maxAmount: null, speedToFunding: "24 hours", creditTier: "fair", minCredit: null, minMonthlyRevenue: 2000, timeInBusiness: "3 months", featured: false },
  { slug: "marketplace-instant-advance", title: "Marketplace Instant Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Marketplace Capital", useCase: "Ecommerce Inventory", summary: "Fast marketplace advance for inventory purchases and seller cash-flow timing.", minAmount: 5000, maxAmount: 250000, speedToFunding: "24 hours", creditTier: "fair", minCredit: null, minMonthlyRevenue: 10000, timeInBusiness: "9 months", featured: false },
  { slug: "business-credit-stacking-plus", title: "Business Credit Stacking Plus", category: "business", parentCategorySlug: "startup-growth-line", fundingType: "Unsecured Line", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Stronger-credit business credit stacking path for founders building a larger launch stack.", minAmount: 10000, maxAmount: 250000, speedToFunding: "2-4 weeks", creditTier: "good", minCredit: 700, minMonthlyRevenue: 0, timeInBusiness: "0 months", featured: false },
  { slug: "business-credit-builder-service", title: "Business Credit Builder Service", category: "business", parentCategorySlug: "startup-growth-line", fundingType: "Service", solutionFamily: "Credit Building", useCase: "Business Credit Building", summary: "Fundability support for businesses that need stronger credit infrastructure before borrowing.", minAmount: null, maxAmount: null, speedToFunding: "n/a", creditTier: "n-a", minCredit: 0, minMonthlyRevenue: 0, timeInBusiness: "0 months", featured: false },
  { slug: "equipment-finance-agreement", title: "Equipment Finance Agreement", category: "business", parentCategorySlug: "equipment-financing", fundingType: "Asset Backed", solutionFamily: "Equipment Finance", useCase: "Equipment Purchase", summary: "Equipment agreement path for moderate-sized asset purchases and replacements.", minAmount: 10000, maxAmount: 500000, speedToFunding: "1-3 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: null, timeInBusiness: "2 years", featured: false },
  { slug: "working-capital-loan", title: "Working Capital Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "General working-capital term loan for active businesses that need structured liquidity.", minAmount: 25000, maxAmount: 5000000, speedToFunding: "24 hours", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 10000, timeInBusiness: "1 year", featured: false },
  { slug: "seller-working-capital", title: "Seller Working Capital", category: "business", parentCategorySlug: "working-capital", fundingType: "Revenue Based", solutionFamily: "Marketplace Capital", useCase: "Ecommerce Inventory", summary: "Seller-focused capital for larger marketplace operators managing inventory growth.", minAmount: 10000, maxAmount: 10000000, speedToFunding: "24-48 hours", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 20000, timeInBusiness: "6 months", featured: false },
  { slug: "retirement-rollover-startup-funding", title: "Retirement Rollover Startup Funding", category: "business", parentCategorySlug: "startup-growth-line", fundingType: "Equity", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Debt-free startup capital path using retirement assets for launch or acquisition.", minAmount: 50000, maxAmount: 5000000, speedToFunding: "3-4 weeks", creditTier: "n-a", minCredit: 0, minMonthlyRevenue: 0, timeInBusiness: "0 months", featured: false },
  { slug: "unsecured-business-finance", title: "Unsecured Business Finance", category: "business", parentCategorySlug: "startup-growth-line", fundingType: "Unsecured Line", solutionFamily: "Startup Funding", useCase: "Startup Capital", summary: "Larger unsecured startup-focused business finance path for strong-credit founders.", minAmount: 25000, maxAmount: 500000, speedToFunding: "10-14 days", creditTier: "good", minCredit: 700, minMonthlyRevenue: 0, timeInBusiness: "0 months", featured: false },
  { slug: "small-business-loan-express", title: "Small Business Loan Express", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Fast small-business term path for active operators who need money quicker than pristine structure.", minAmount: 5000, maxAmount: 500000, speedToFunding: "24-72 hours", creditTier: "subprime", minCredit: 500, minMonthlyRevenue: 12000, timeInBusiness: "6 months", featured: false },
  { slug: "revenue-advance-express", title: "Revenue Advance Express", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Payroll Gap", summary: "Rapid advance lane for urgent revenue-backed cash needs and compressed timelines.", minAmount: 5000, maxAmount: 500000, speedToFunding: "24 hours", creditTier: "subprime", minCredit: 500, minMonthlyRevenue: 12000, timeInBusiness: "6 months", featured: false },
  { slug: "fast-working-capital-loan", title: "Fast Working Capital Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Working Capital", useCase: "Payroll Gap", summary: "Quick-turn term capital for active businesses under cash timing pressure.", minAmount: 5000, maxAmount: 600000, speedToFunding: "24 hours", creditTier: "subprime", minCredit: 500, minMonthlyRevenue: 15000, timeInBusiness: "6 months", featured: false },
  { slug: "business-expansion-loan", title: "Business Expansion Loan", category: "business", parentCategorySlug: "working-capital", fundingType: "Term Loan", solutionFamily: "Structured Growth", useCase: "Expansion Capital", summary: "Expansion-oriented term product for businesses that are growing but not fully prime.", minAmount: 5000, maxAmount: 600000, speedToFunding: "3-5 days", creditTier: "fair", minCredit: 600, minMonthlyRevenue: 15000, timeInBusiness: "6 months", featured: false },
  { slug: "fast-merchant-advance", title: "Fast Merchant Advance", category: "business", parentCategorySlug: "merchant-cash-advance", fundingType: "Revenue Advance", solutionFamily: "Working Capital", useCase: "Working Capital", summary: "Merchant-style advance for operators who need fast liquidity and can support frequent repayment.", minAmount: 5000, maxAmount: 500000, speedToFunding: "24 hours", creditTier: "subprime", minCredit: 500, minMonthlyRevenue: 10000, timeInBusiness: "6 months", featured: false },
  { slug: "dscr-rental-loan", title: "DSCR Rental Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Mortgage", solutionFamily: "Real Estate Capital", useCase: "Real Estate Acquisition", summary: "Income-property financing built around rental cash flow instead of traditional income docs.", minAmount: 75000, maxAmount: 5000000, speedToFunding: "3-4 weeks", creditTier: "good", minCredit: 680, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: false },
  { slug: "fix-and-flip-bridge-loan", title: "Fix and Flip Bridge Loan", category: "real-estate", parentCategorySlug: "working-capital", fundingType: "Hard Money", solutionFamily: "Real Estate Capital", useCase: "Fix and Flip", summary: "Bridge capital for acquisitions, rehab timelines, and short-term property exit strategies.", minAmount: 100000, maxAmount: 5000000, speedToFunding: "5-7 days", creditTier: "fair", minCredit: 650, minMonthlyRevenue: null, timeInBusiness: "n/a", featured: true },
];
