export type Tool = {
  slug: string;
  title: string;
  summary: string;
  outcome: string;
  estimatedTime: string;
  idealFor: string;
  signalInputs: string[];
  primaryMetric: string;
  funnelStage: string;
  ctaLabel: string;
};

export const tools: Tool[] = [
  {
    slug: "funding-match",
    title: "Funding Match",
    summary: "Match operators to the most relevant Moonshine funding category using qualification signals.",
    outcome: "Outputs the top funding path with a confidence score.",
    estimatedTime: "3 minutes",
    idealFor: "Inbound traffic and partner referrals",
    signalInputs: ["Monthly revenue", "Time in business", "Funding objective"],
    primaryMetric: "Match confidence",
    funnelStage: "Discovery to qualification",
    ctaLabel: "Launch matcher",
  },
  {
    slug: "startup-planner",
    title: "Startup Planner",
    summary: "Model runway, burn phases, and milestone financing needs for early-stage execution.",
    outcome: "Generates a quarter-by-quarter capital plan.",
    estimatedTime: "5 minutes",
    idealFor: "Pre-seed to Series A teams",
    signalInputs: ["Burn rate", "Hiring plan", "Milestone targets"],
    primaryMetric: "Runway projection",
    funnelStage: "Planning and readiness",
    ctaLabel: "Plan runway",
  },
  {
    slug: "revenue-estimator",
    title: "Revenue Estimator",
    summary: "Estimate likely funding capacity based on monthly revenue, margin profile, and cash cycle.",
    outcome: "Shows projected offer range and readiness score.",
    estimatedTime: "4 minutes",
    idealFor: "Revenue-generating SMB operators",
    signalInputs: ["Gross revenue", "Margin profile", "Receivable cycle"],
    primaryMetric: "Readiness score",
    funnelStage: "Qualification before apply",
    ctaLabel: "Run estimate",
  },
  {
    slug: "lead-capture-form",
    title: "Lead Capture Form",
    summary: "Embedded intake form for capturing funding inquiries directly into the marketplace flow.",
    outcome: "Captures tracked lead context before application handoff.",
    estimatedTime: "2 minutes",
    idealFor: "Partner websites and landing pages",
    signalInputs: ["Use of funds", "Revenue", "Contact info"],
    primaryMetric: "Qualified lead rate",
    funnelStage: "Initial capture",
    ctaLabel: "Open form spec",
  },
  {
    slug: "document-checklist-builder",
    title: "Document Checklist Builder",
    summary: "Build product-specific document checklists based on use case, urgency, and fit.",
    outcome: "Generates a tailored doc checklist for cleaner submissions.",
    estimatedTime: "3 minutes",
    idealFor: "Brokers, advisors, and intake operators",
    signalInputs: ["Product path", "Borrower type", "Urgency level"],
    primaryMetric: "Submission readiness",
    funnelStage: "Qualification to submission",
    ctaLabel: "Build checklist",
  },
  {
    slug: "readiness-quiz",
    title: "Funding Readiness Quiz",
    summary: "Quick prequalification experience that scores how ready a borrower is before deeper review.",
    outcome: "Returns readiness tier and suggested next action.",
    estimatedTime: "4 minutes",
    idealFor: "Top-of-funnel leads and self-serve users",
    signalInputs: ["Credit range", "Time in business", "Doc readiness"],
    primaryMetric: "Readiness tier",
    funnelStage: "Discovery",
    ctaLabel: "Take quiz",
  },
  {
    slug: "revenue-advance-estimator",
    title: "Revenue Advance Estimator",
    summary: "Scenario estimator for advance-style capital using revenue and urgency inputs.",
    outcome: "Projects range, cadence expectations, and fit notes.",
    estimatedTime: "3 minutes",
    idealFor: "Working-capital prospects",
    signalInputs: ["Monthly revenue", "Cash urgency", "Average deposits"],
    primaryMetric: "Projected advance range",
    funnelStage: "Qualification",
    ctaLabel: "Estimate advance",
  },
  {
    slug: "equipment-finance-estimator",
    title: "Equipment Finance Estimator",
    summary: "Estimate monthly scenarios and likely fit for equipment-backed requests.",
    outcome: "Projects estimated range and repayment framing.",
    estimatedTime: "3 minutes",
    idealFor: "Equipment buyers and operators replacing productive assets",
    signalInputs: ["Equipment cost", "Down payment", "Business profile"],
    primaryMetric: "Estimated monthly payment band",
    funnelStage: "Qualification",
    ctaLabel: "Estimate equipment fit",
  },
  {
    slug: "seller-analyzer",
    title: "Seller Analyzer",
    summary: "Marketplace-oriented analyzer for sellers needing inventory and payout-speed support.",
    outcome: "Returns marketplace-capital fit and likely use-case path.",
    estimatedTime: "4 minutes",
    idealFor: "Amazon, Walmart, and social sellers",
    signalInputs: ["Platform revenue", "Seller tenure", "Inventory need"],
    primaryMetric: "Marketplace fit score",
    funnelStage: "Qualification",
    ctaLabel: "Analyze seller fit",
  },
  {
    slug: "dscr-snapshot",
    title: "DSCR Snapshot",
    summary: "Property-level snapshot tool for rent, DSCR, leverage, and hold assumptions.",
    outcome: "Surfaces likely DSCR-style fit and next-step property questions.",
    estimatedTime: "4 minutes",
    idealFor: "Rental-property investors",
    signalInputs: ["Rent", "Debt service", "Property value"],
    primaryMetric: "Projected DSCR",
    funnelStage: "Property qualification",
    ctaLabel: "Run DSCR snapshot",
  },
  {
    slug: "fix-flip-snapshot",
    title: "Fix-and-Flip Snapshot",
    summary: "Quick intake tool for ARV, rehab scope, exit timing, and bridge-loan logic.",
    outcome: "Returns a deal-readiness snapshot for bridge or hard-money routing.",
    estimatedTime: "4 minutes",
    idealFor: "Flippers and short-term investors",
    signalInputs: ["Purchase price", "ARV", "Rehab budget"],
    primaryMetric: "Bridge-fit snapshot",
    funnelStage: "Property qualification",
    ctaLabel: "Run deal snapshot",
  },
  {
    slug: "partner-link-generator",
    title: "Partner Link Generator",
    summary: "Create tracked referral links with partner, UTM, and asset attribution baked in.",
    outcome: "Outputs attribution-safe partner URLs.",
    estimatedTime: "2 minutes",
    idealFor: "Partners and distribution operators",
    signalInputs: ["Partner ID", "Campaign", "Asset ID"],
    primaryMetric: "Tracked link coverage",
    funnelStage: "Distribution setup",
    ctaLabel: "Generate link",
  },
  {
    slug: "advisor-card-spec",
    title: "Advisor Card Spec",
    summary: "Embeddable advisor-profile module spec for partner pages, sidebars, or footers.",
    outcome: "Creates a standardized advisor widget definition.",
    estimatedTime: "2 minutes",
    idealFor: "Partner pages and co-branded assets",
    signalInputs: ["Advisor name", "Role", "Referral code"],
    primaryMetric: "Advisor placement coverage",
    funnelStage: "Conversion support",
    ctaLabel: "Open spec",
  },
  {
    slug: "offer-comparison-table",
    title: "Offer Comparison Table",
    summary: "Internal comparison layer to contrast capital paths without exposing backend sources.",
    outcome: "Returns a side-by-side view of fit, speed, and qualification differences.",
    estimatedTime: "3 minutes",
    idealFor: "Advisors and closers",
    signalInputs: ["Use case", "Speed need", "Credit tier"],
    primaryMetric: "Decision clarity",
    funnelStage: "Routing and advisory",
    ctaLabel: "Compare offers",
  },
  {
    slug: "follow-up-sequence-generator",
    title: "Follow-Up Sequence Generator",
    summary: "Generate follow-up messaging for prospects who stall, ghost, or need doc nudges.",
    outcome: "Outputs stage-aware follow-up messages and next-step prompts.",
    estimatedTime: "3 minutes",
    idealFor: "Brokers and partner reps",
    signalInputs: ["Lead stage", "Objection", "Pending requirement"],
    primaryMetric: "Follow-up speed",
    funnelStage: "Post-qualification nurture",
    ctaLabel: "Generate follow-up",
  },
];
