export type Vertical = {
  slug: string;
  title: string;
  summary: string;
  operatorProfile: string;
  painPoint: string;
  marketSignal: string;
  featuredFundingSlug: string;
  recommendedToolSlug: string;
  capitalUseCases: string[];
  keyKpis: string[];
};

export const verticals: Vertical[] = [
  {
    slug: "saas",
    title: "SaaS",
    summary: "Recurring revenue teams scaling pipeline velocity and retention infrastructure.",
    operatorProfile: "Founder-led SaaS businesses with established recurring revenue and pipeline momentum.",
    painPoint: "Customer acquisition ramps faster than available working runway.",
    marketSignal: "Median payback windows compress when funded GTM systems are deployed.",
    featuredFundingSlug: "startup-growth-line",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["CAC expansion", "Product and engineering hires", "Customer success scaling"],
    keyKpis: ["MRR growth", "CAC payback", "Net revenue retention"],
  },
  {
    slug: "healthcare",
    title: "Healthcare",
    summary: "Provider and service operators balancing compliance, staff expansion, and equipment intensity.",
    operatorProfile: "Clinic owners and service operators expanding capacity while maintaining compliance standards.",
    painPoint: "Credentialing timelines and delayed reimbursements create capital pressure.",
    marketSignal: "Operational throughput climbs with modernized equipment and staffing depth.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Diagnostic equipment upgrades", "Provider hiring ramp", "Facility throughput expansion"],
    keyKpis: ["Provider utilization", "Days in AR", "Appointment throughput"],
  },
  {
    slug: "logistics",
    title: "Logistics",
    summary: "Freight and fleet operators managing fuel volatility, payroll cadence, and route expansion.",
    operatorProfile: "Fleet-based operators with repeat contracts and working-capital-heavy dispatch cycles.",
    painPoint: "Cash conversion gaps between delivery execution and customer settlement.",
    marketSignal: "Route density and asset uptime are direct drivers of margin expansion.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Fuel and payroll bridge", "Fleet maintenance cycles", "Route expansion support"],
    keyKpis: ["Fleet utilization", "On-time delivery", "Gross margin per route"],
  },
  {
    slug: "hospitality",
    title: "Hospitality",
    summary: "Multi-location operators planning around seasonal demand and labor swings.",
    operatorProfile: "Restaurant and hospitality teams balancing guest demand with staffing and inventory timing.",
    painPoint: "Peak demand periods require inventory and staff spending before revenue arrives.",
    marketSignal: "Advanced prep financing consistently improves peak-season capture rates.",
    featuredFundingSlug: "merchant-cash-advance",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Seasonal inventory prep", "Labor scheduling ramp", "Location refresh and capacity"],
    keyKpis: ["Average ticket size", "Table turn rate", "Seasonal revenue lift"],
  },
  {
    slug: "home-services",
    title: "Home Services",
    summary: "Field-service businesses funding truck fleets, technicians, and job volume spikes.",
    operatorProfile: "Service businesses with strong lead flow and scaling technician operations.",
    painPoint: "Growth in booked jobs can outpace available labor and equipment capital.",
    marketSignal: "Speed-to-dispatch and close rates improve with pre-funded capacity.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Vehicle additions", "Technician onboarding", "High-volume job fulfillment"],
    keyKpis: ["Job close rate", "Technician utilization", "Average response time"],
  },
  {
    slug: "ecommerce",
    title: "Ecommerce",
    summary: "Operators balancing inventory timing, ad spend, and cash conversion pressure.",
    operatorProfile: "Direct-to-consumer and multi-channel brands with meaningful online sales velocity.",
    painPoint: "Inventory and ad spend must be front-loaded before the revenue cycle catches up.",
    marketSignal: "Brands that keep stock depth and campaign momentum tend to capture outsized growth windows.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Inventory buys", "Ad spend scaling", "Fulfillment smoothing"],
    keyKpis: ["Contribution margin", "Inventory turns", "ROAS"],
  },
  {
    slug: "amazon-sellers",
    title: "Amazon Sellers",
    summary: "Marketplace-native merchants needing inventory and payout-speed support.",
    operatorProfile: "Amazon sellers with steady account health and platform-linked performance data.",
    painPoint: "Cash gets trapped between inventory purchase timing and marketplace disbursement cycles.",
    marketSignal: "Sellers with healthy account metrics can often move faster through platform-aware funding paths.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Restock inventory", "Seller account growth", "Marketplace cash-flow support"],
    keyKpis: ["Seller rating", "Inventory days", "Ad efficiency"],
  },
  {
    slug: "contractors",
    title: "Contractors",
    summary: "Trade operators managing materials, crews, and receivable timing under project pressure.",
    operatorProfile: "General contractors and specialty trades with active project pipelines.",
    painPoint: "Projects require labor and material deployment before collections arrive.",
    marketSignal: "Operators with tight estimating and collections discipline can scale faster with the right working capital.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Materials bridge", "Crew payroll", "Project mobilization"],
    keyKpis: ["Backlog", "Gross margin", "Days sales outstanding"],
  },
  {
    slug: "construction",
    title: "Construction",
    summary: "Builders and subs financing equipment, mobilization, and project cadence.",
    operatorProfile: "Construction businesses managing equipment-heavy operations and milestone billing.",
    painPoint: "Capital gets tied up between mobilization, billing, and customer settlement.",
    marketSignal: "Asset-backed financing and receivable support are often the cleanest levers for growth.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Heavy equipment", "Payroll bridge", "Mobilization costs"],
    keyKpis: ["Backlog conversion", "Utilization", "Project gross margin"],
  },
  {
    slug: "retail",
    title: "Retail",
    summary: "Store operators planning around inventory cycles, staffing, and seasonal demand spikes.",
    operatorProfile: "Retail owners with repeat foot traffic and seasonal buying patterns.",
    painPoint: "Stock and payroll need to be funded before the next revenue surge hits.",
    marketSignal: "Retailers that prepare inventory depth ahead of demand windows tend to capture outsized seasonal lift.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Inventory prep", "Store refreshes", "Seasonal staffing"],
    keyKpis: ["Sell-through rate", "Average basket", "Seasonal revenue lift"],
  },
  {
    slug: "restaurants",
    title: "Restaurants",
    summary: "Operators managing payroll, food costs, and demand spikes in a margin-sensitive business.",
    operatorProfile: "Independent and multi-unit restaurant owners with strong card volume.",
    painPoint: "Cash gets squeezed between labor, food purchasing, and the next wave of receipts.",
    marketSignal: "Restaurants with tight operational discipline often need speed more than complexity.",
    featuredFundingSlug: "merchant-cash-advance",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Payroll", "Equipment replacement", "Seasonal prep"],
    keyKpis: ["Daily sales", "Prime cost", "Table turns"],
  },
  {
    slug: "trucking",
    title: "Trucking",
    summary: "Owner-operators and fleets financing trucks, trailers, and repair-driven downtime.",
    operatorProfile: "Transportation businesses where asset uptime directly drives revenue capacity.",
    painPoint: "A truck down is revenue down, and repairs rarely wait for better timing.",
    marketSignal: "Repair-to-revenue logic makes equipment and bridge capital especially useful in this segment.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Truck purchase", "Repair bridge", "Fleet expansion"],
    keyKpis: ["Revenue per truck", "Utilization", "Maintenance downtime"],
  },
  {
    slug: "manufacturing",
    title: "Manufacturing",
    summary: "Operators financing machinery, materials, and longer cash conversion cycles.",
    operatorProfile: "Manufacturing businesses with capex demands and inventory-heavy throughput.",
    painPoint: "Cash gets trapped in materials, production lead times, and extended receivables.",
    marketSignal: "A mix of equipment finance and receivables support often creates cleaner growth than generic loans.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Machine upgrades", "Raw material purchases", "Production scaling"],
    keyKpis: ["Throughput", "Backlog", "Inventory turns"],
  },
  {
    slug: "wholesale-distribution",
    title: "Wholesale & Distribution",
    summary: "Operators balancing purchasing cycles, warehouse cash needs, and customer payment timing.",
    operatorProfile: "Wholesalers and distributors with invoice-driven revenue and purchasing pressure.",
    painPoint: "Stock must be bought before invoices are paid, squeezing cash conversion.",
    marketSignal: "Inventory and receivable awareness matter more here than generic balance-sheet storytelling.",
    featuredFundingSlug: "invoice-factoring",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Purchase orders", "Warehouse cash-flow support", "Receivable bridge"],
    keyKpis: ["Inventory turns", "Gross margin", "DSO"],
  },
  {
    slug: "real-estate-investors",
    title: "Real Estate Investors",
    summary: "Investors buying, stabilizing, flipping, or refinancing income-producing property.",
    operatorProfile: "Rental and flip operators with deal flow and clear property strategies.",
    painPoint: "Timing and structure matter more than generic borrower messaging in real estate.",
    marketSignal: "Bridge, DSCR, and commercial paths each serve different repayment logic and exit plans.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Acquisition", "Fix-and-flip", "Rental refi"],
    keyKpis: ["DSCR", "LTV", "Exit timeline"],
  },
  {
    slug: "franchise-operators",
    title: "Franchise Operators",
    summary: "Operators launching or expanding proven franchise systems with structured growth needs.",
    operatorProfile: "Franchisees with unit economics, growth plans, and brand-operating discipline.",
    painPoint: "Expansion timing, build-out costs, and labor needs can outrun internal cash reserves.",
    marketSignal: "Franchise-friendly structured capital tends to outperform generic one-size-fits-all working-capital paths.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["Unit launch", "Equipment", "Expansion capital"],
    keyKpis: ["Same-store sales", "Payback window", "Unit economics"],
  },
  {
    slug: "creators",
    title: "Creators",
    summary: "Audience-led operators monetizing content, products, services, and digital distribution.",
    operatorProfile: "Creators and media-first businesses with growing revenue but uneven traditional underwriting optics.",
    painPoint: "Digital businesses often have real demand but messy funding narratives.",
    marketSignal: "The cleaner the revenue story, the easier it is to route creators into practical capital paths.",
    featuredFundingSlug: "startup-growth-line",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["Production scaling", "Product launches", "Media team expansion"],
    keyKpis: ["Audience conversion", "Revenue diversification", "Launch performance"],
  },
];
