export type Vertical = {
  slug: string;
  title: string;
  segment: string;
  summary: string;
  operatorProfile: string;
  painPoint: string;
  marketSignal: string;
  featuredFundingSlug: string;
  recommendedToolSlug: string;
  capitalUseCases: string[];
  keyKpis: string[];
  bestFitCapitalPaths: string[];
};

export const verticals: Vertical[] = [
  {
    slug: "startups",
    title: "Startups",
    segment: "early-stage",
    summary: "Founders trying to launch, validate, and survive the dangerous gap between idea and stable operating momentum.",
    operatorProfile: "Early-stage founders with a real plan but limited business history.",
    painPoint: "Most startups need capital before traditional underwriting thinks they deserve oxygen.",
    marketSignal: "The stronger the founder story, personal credit profile, and revenue traction, the more realistic the capital menu becomes.",
    featuredFundingSlug: "startup-growth-line",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["Launch capital", "Early hiring", "Go-to-market runway"],
    keyKpis: ["Runway", "Burn rate", "Early revenue traction"],
    bestFitCapitalPaths: ["Startup Growth Line", "Startup Credit Stacking", "Founder Launch Loan", "Retirement Rollover Startup Funding"],
  },
  {
    slug: "solopreneurs",
    title: "Solopreneurs",
    segment: "owner-operator",
    summary: "Lean operators wearing every hat and needing capital that respects speed, simplicity, and actual cash flow.",
    operatorProfile: "One-person businesses with uneven but real operating momentum.",
    painPoint: "They usually need useful money, not a 90-day underwriting opera.",
    marketSignal: "Clear deposits and disciplined use of funds matter more than fancy pitch decks here.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Cash-flow smoothing", "Marketing spend", "Contract fulfillment"],
    keyKpis: ["Monthly deposits", "Gross margin", "Lead-to-close rate"],
    bestFitCapitalPaths: ["Working Capital", "Business Line of Credit", "Small Business Loan Express"],
  },
  {
    slug: "consultants",
    title: "Consultants",
    segment: "professional-services",
    summary: "Service operators with strong margins, uneven collections, and clients who love Net-30 when it is your money on the line.",
    operatorProfile: "Consultants and boutique advisors with recurring retainers or project revenue.",
    painPoint: "Receivable timing can choke a healthy business faster than lack of demand.",
    marketSignal: "The cleaner the invoicing and collections story, the easier it is to route them into structured working capital.",
    featuredFundingSlug: "invoice-factoring",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Payroll bridge", "Contractor payments", "Growth marketing"],
    keyKpis: ["DSO", "Utilization", "Retainer retention"],
    bestFitCapitalPaths: ["Invoice Factoring", "Working Capital", "Business Line of Credit"],
  },
  {
    slug: "agencies",
    title: "Agencies",
    segment: "professional-services",
    summary: "Agencies balancing payroll, media spend, contractor costs, and clients who magically think invoices are optional.",
    operatorProfile: "Marketing, creative, recruiting, and service agencies with active client books.",
    painPoint: "Labor and delivery costs hit before receivables clear.",
    marketSignal: "Agencies with strong gross margins and stable retainers tend to qualify more cleanly than they expect.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Payroll", "Ad spend float", "Client delivery capacity"],
    keyKpis: ["Gross margin", "Monthly recurring revenue", "Client retention"],
    bestFitCapitalPaths: ["Working Capital", "Business Credit Line", "Accounts Receivable Financing"],
  },
  {
    slug: "b2b-saas",
    title: "B2B SaaS",
    segment: "technology",
    summary: "Recurring-revenue software teams scaling pipeline, product delivery, and retention infrastructure.",
    operatorProfile: "Founder-led software businesses with real MRR and defined growth goals.",
    painPoint: "Customer acquisition usually accelerates faster than available runway.",
    marketSignal: "If the growth story is real and the burn is controlled, capital becomes a lever instead of a liability.",
    featuredFundingSlug: "startup-growth-line",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["Customer acquisition", "Product hiring", "Runway extension"],
    keyKpis: ["MRR growth", "CAC payback", "NRR"],
    bestFitCapitalPaths: ["Startup Growth Line", "Growth Term Loan", "Business Expansion Loan"],
  },
  {
    slug: "ecommerce-brands",
    title: "Ecommerce Brands",
    segment: "commerce",
    summary: "Operators trying to keep inventory in stock, ads live, and cash conversion from turning into a street fight.",
    operatorProfile: "Direct-to-consumer and omni-channel brands with meaningful online sales velocity.",
    painPoint: "Inventory and marketing spend have to be paid before the revenue arrives.",
    marketSignal: "The stronger the inventory cycle and ad economics, the more useful marketplace and working-capital routes become.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Inventory purchases", "Ad spend scaling", "Fulfillment smoothing"],
    keyKpis: ["Inventory turns", "Contribution margin", "ROAS"],
    bestFitCapitalPaths: ["Working Capital", "Ecommerce Growth Plan", "Seller Working Capital"],
  },
  {
    slug: "amazon-sellers",
    title: "Amazon Sellers",
    segment: "marketplace",
    summary: "Marketplace-native sellers who need capital aligned to inventory timing, payout cycles, and account performance.",
    operatorProfile: "Amazon operators with meaningful sales history and stable account health.",
    painPoint: "Cash gets trapped between inventory orders and marketplace disbursement timing.",
    marketSignal: "Platform-linked capital usually beats generic guessing when seller data is strong.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "seller-analyzer",
    capitalUseCases: ["Restock inventory", "Seasonal prep", "Ad scaling"],
    keyKpis: ["Account health", "Inventory days", "Ad efficiency"],
    bestFitCapitalPaths: ["Marketplace Growth Capital", "Marketplace Instant Advance", "Daily Payout Access"],
  },
  {
    slug: "walmart-sellers",
    title: "Walmart Sellers",
    segment: "marketplace",
    summary: "Marketplace sellers balancing catalog expansion, inventory needs, and payout timing across a retail-native platform.",
    operatorProfile: "Walmart sellers with growing order volume and a need for cleaner cash flow.",
    painPoint: "Inventory and shipping commitments hit before revenue settles.",
    marketSignal: "Operators with healthy seller performance and consistent revenue can often fit marketplace-aware capital routes.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "seller-analyzer",
    capitalUseCases: ["Inventory depth", "Channel expansion", "Cash-flow smoothing"],
    keyKpis: ["Seller performance", "Revenue velocity", "Inventory turn"],
    bestFitCapitalPaths: ["Marketplace Growth Capital", "Seller Working Capital", "Working Capital"],
  },
  {
    slug: "tiktok-shop-sellers",
    title: "TikTok Shop Sellers",
    segment: "marketplace",
    summary: "Fast-moving social-commerce operators with spiky demand, inventory pressure, and a need for speed over ceremony.",
    operatorProfile: "Social sellers with growing order volume and short decision cycles.",
    painPoint: "Trend-driven sales can explode before inventory and cash reserves are ready.",
    marketSignal: "The faster the product movement, the more valuable fast inventory-oriented capital becomes.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "seller-analyzer",
    capitalUseCases: ["Trend inventory buys", "Creator campaign spend", "Order fulfillment"],
    keyKpis: ["Conversion rate", "Inventory velocity", "Channel growth"],
    bestFitCapitalPaths: ["Marketplace Instant Advance", "Ecommerce Growth Plan", "Fast Working Capital Advance"],
  },
  {
    slug: "restaurants",
    title: "Restaurants",
    segment: "hospitality",
    summary: "Operators managing payroll, food costs, repairs, and seasonal demand in a business where margins bruise easily.",
    operatorProfile: "Independent and multi-unit restaurant owners with active card volume.",
    painPoint: "Cash gets squeezed between labor, food ordering, and the next wave of receipts.",
    marketSignal: "Restaurants often need speed and practicality more than elaborate capital structures.",
    featuredFundingSlug: "merchant-cash-advance",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Payroll", "Equipment replacement", "Seasonal prep"],
    keyKpis: ["Daily sales", "Prime cost", "Table turns"],
    bestFitCapitalPaths: ["Merchant Cash Advance", "Fast Working Capital Advance", "Equipment Financing"],
  },
  {
    slug: "contractors",
    title: "Contractors",
    segment: "home-services",
    summary: "Trade operators trying to keep crews moving, materials paid, and jobs funded before collections clear.",
    operatorProfile: "General contractors and specialty trades with active project pipelines.",
    painPoint: "Mobilization, materials, and payroll usually hit before the money comes back.",
    marketSignal: "Good contractors do not need hype. They need capital that respects job timing.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "document-checklist-builder",
    capitalUseCases: ["Materials bridge", "Crew payroll", "Project mobilization"],
    keyKpis: ["Backlog", "Gross margin", "Collections speed"],
    bestFitCapitalPaths: ["Working Capital", "Accounts Receivable Financing", "Equipment Financing"],
  },
  {
    slug: "trucking",
    title: "Trucking",
    segment: "transportation",
    summary: "Owner-operators and fleets financing trucks, repairs, and the brutal reality that a truck down means revenue down.",
    operatorProfile: "Transportation businesses where uptime directly drives revenue capacity.",
    painPoint: "Repair, maintenance, and acquisition needs do not politely wait for better timing.",
    marketSignal: "Equipment and repair-oriented capital usually matters more here than generic business-loan fluff.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Truck purchase", "Repair bridge", "Fleet expansion"],
    keyKpis: ["Revenue per truck", "Utilization", "Maintenance downtime"],
    bestFitCapitalPaths: ["Commercial Truck Finance", "Equipment Finance Program", "Fast Working Capital Loan"],
  },
  {
    slug: "logistics",
    title: "Logistics",
    segment: "transportation",
    summary: "Freight and dispatch operators managing fuel volatility, payroll cadence, and route expansion under constant timing pressure.",
    operatorProfile: "Fleet-based operators with repeat contracts and working-capital-heavy dispatch cycles.",
    painPoint: "Cash conversion gaps between service execution and customer settlement.",
    marketSignal: "Route density and asset uptime are direct drivers of margin expansion.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "funding-match",
    capitalUseCases: ["Fuel and payroll bridge", "Fleet maintenance", "Route expansion"],
    keyKpis: ["Fleet utilization", "On-time delivery", "Gross margin per route"],
    bestFitCapitalPaths: ["Working Capital", "Invoice Factoring", "Commercial Truck Finance"],
  },
  {
    slug: "healthcare",
    title: "Healthcare",
    segment: "healthcare",
    summary: "Provider and service operators balancing compliance, staffing, throughput, and equipment intensity.",
    operatorProfile: "Clinic owners and healthcare operators expanding capacity while maintaining compliance standards.",
    painPoint: "Credentialing delays, staffing pressure, and reimbursement timing create real capital drag.",
    marketSignal: "Healthcare operators often fit structured equipment and growth routes better than generic fast money.",
    featuredFundingSlug: "equipment-financing",
    recommendedToolSlug: "revenue-estimator",
    capitalUseCases: ["Equipment upgrades", "Provider hiring", "Capacity expansion"],
    keyKpis: ["Provider utilization", "Days in AR", "Appointment throughput"],
    bestFitCapitalPaths: ["Equipment Financing", "Growth Term Loan", "SBA Growth Loan"],
  },
  {
    slug: "franchise-owners",
    title: "Franchise Owners",
    segment: "franchise",
    summary: "Operators launching or expanding proven franchise systems with cleaner growth logic than most independent startups.",
    operatorProfile: "Franchisees with unit economics, brand discipline, and expansion intent.",
    painPoint: "Build-out, labor, and launch timing can outrun internal reserves fast.",
    marketSignal: "Franchise-friendly structured capital usually beats forcing these operators into random short-term products.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["Unit launch", "Equipment", "Expansion capital"],
    keyKpis: ["Same-store sales", "Payback window", "Unit economics"],
    bestFitCapitalPaths: ["Franchise Financing", "SBA Expansion Loan", "Business Expansion Loan"],
  },
  {
    slug: "real-estate-investors",
    title: "Real Estate Investors",
    segment: "real-estate",
    summary: "Investors buying, stabilizing, flipping, or refinancing property where structure matters more than motivational speeches.",
    operatorProfile: "Rental and flip investors with real deal flow and clear property strategies.",
    painPoint: "Timing and repayment logic are everything in property-backed capital.",
    marketSignal: "Bridge, DSCR, and mortgage routes serve very different games. Mixing them lazily is how deals die.",
    featuredFundingSlug: "working-capital",
    recommendedToolSlug: "fix-flip-snapshot",
    capitalUseCases: ["Acquisition", "Fix-and-flip", "Rental refinance"],
    keyKpis: ["DSCR", "LTV", "Exit timeline"],
    bestFitCapitalPaths: ["Fix and Flip Bridge Loan", "DSCR Rental Loan", "Commercial Real Estate Financing"],
  },
  {
    slug: "creators",
    title: "Creators",
    segment: "digital-business",
    summary: "Audience-led operators monetizing content, products, communities, and digital offers with real demand but messy lender optics.",
    operatorProfile: "Creators and media-first businesses with growing revenue and unconventional operating models.",
    painPoint: "Digital businesses often have real momentum but ugly paperwork narratives.",
    marketSignal: "The cleaner the revenue story, the easier it is to route creators into practical capital instead of shrugging at them.",
    featuredFundingSlug: "startup-growth-line",
    recommendedToolSlug: "startup-planner",
    capitalUseCases: ["Production scaling", "Product launches", "Audience monetization infrastructure"],
    keyKpis: ["Revenue diversification", "Launch performance", "Audience conversion"],
    bestFitCapitalPaths: ["Startup Growth Line", "Working Capital", "Business Line of Credit"],
  },
];
